[package]
name = "snifferrs"
version = "0.0.1"
edition = "2021"

[dependencies]
colored = "2"
httparse = "1.3.4"
libpcap = "0.1.7"
hex = "0.4.2"
data-encoding = "2.1.0"
netraffic = "0.1.0"
lazy_static = "1.4.0"
